### PR TITLE
fix displaying "This submission may contain copyright violations"

### LINKED ISSUE #324: Displaying "This submission may contain copyright violations" is broken
There is code in AFCH to display "This submission may contain copyright violations" if the Turnitin API detects the draft to be a copyright violation. This is handled by User:CopyPatrolBot and the pagetriagetagcopyvio API.

However I can't recall ever having seen this warning in AFCH.

When I clicked open 25 of the [latest drafts tagged as copyvio](https://en.wikipedia.org/wiki/Special:Log?type=pagetriage-copyvio&user=&page=&wpdate=&tagfilter=&wpfilters%5B%5D=newusers&wpFormIdentifier=logeventslist) just now, I could not get the warning to show up.

https://en.wikipedia.org/wiki/Draft:2028_United_States_presidential_election_in_Massachusetts only has one revision, so the `triageInfo && triageInfo.copyvio === mw.config.get( 'wgCurRevisionId' )` line of code should be satisfied. I can't think of a reason for this warning not to show up on that draft.

I think this feature is completely broken. Needs fixing.

Will debug this once I receive `copyviobot` permissions on testwiki: https://test.wikipedia.org/wiki/Wikipedia:Requests/Permissions/Novem_Linguae_4

### PR DESCRIPTION
**Pull request by NovemLinguae**
fix #324

Was comparing string to int. One fix is to change `===` to `==`

### CODE REVIEW

File: src/modules/submissions.js [hunk 1]
```diff
@@ -1157,7 +1157,7 @@
 				page_id: mw.config.get( 'wgArticleId' )
 			} ).then( function ( json ) {
 				var triageInfo = json.pagetriagelist.pages[ 0 ];
-				if ( triageInfo && triageInfo.copyvio === mw.config.get( 'wgCurRevisionId' ) ) {
+				if ( triageInfo && triageInfo.copyvio == mw.config.get( 'wgCurRevisionId' ) ) {
```
Comment (siddharthvp) [inline src/modules/submissions.js:1160]:
```suggestion
				if ( triageInfo && triageInfo.copyvio === String( mw.config.get( 'wgCurRevisionId' ) ) ) {
```

Might be better to be explicit, as IDEs view use of `==` as suspicious.
